version: "2.2"
services:
  asir_bind9:
    image: internetsystemsconsortium/bind9:9.16
    ports:
      - 53:53
    volumes:
      - conf:/etc/bind
  asir_cliente:
    image: ubuntu
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
volumes:
  conf: